framework:
    messenger:
        default_bus: 'command.bus'
        buses:
            command.bus: ~
            query.bus: ~
        transports:
            sync: 'sync://'
        routing:
            'App\Command\CommandInterface': sync