version: "3"

server:
#    command: "php bin/console baldinof:roadrunner:worker"
    command: "php public/index.php"
    env:
        -   APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime
        -   PHP_IDE_CONFIG: 'serverName=books_directory'

http:
    address: 0.0.0.0:8080
    middleware: [ "static", "gzip" ]
    pool:
        num_workers: 1
        debug: true
    uploads:
        forbid: [ ".php", ".exe", ".bat" ]
    static:
        dir: "public"
        forbid: [ ".php", ".htaccess" ]

#http:
#    address: 0.0.0.0:8000
#    middleware: [ "static" ]
#    static:
#        dir: "./public"
##        forbid: [ ".php" ]
#        weak: false
#    pool:
#        num_workers: 1
#        debug: true

logs:
    mode: development
    channels:
        http:
            level: debug # Log all http requests, set to info to disable
        server:
            level: info # Everything written to worker stderr is logged
            mode: raw
        metrics:
            level: debug

reload:
    enabled: true
    interval: 1s
    patterns: [".php", ".yaml", ".xml"]
    services:
        http:
            recursive: true
            dirs: ["."]
            ignore: ["var", "vendor", ".git", ".idea"]
